const mongoose = require("mongoose");
const Schema = mongoose.Schema;

//User Schema

const userSchema = new Schema(
  {
    //ID will be generated by MongoDB by default in every Schema with the name "_id"
    email: {
      type: String,
      trim: true,
      required: true,
    },
    name: {
      type: String,
      required: true, //Databse will see for this always
      maxlength: 32,
      trim: true,
    },

    mobile: {
      type: Number,
      required: true,
      trim: true,
    },
  }
  // { timestamps: true }
);

//throw this schema out of this file to use further
module.exports = mongoose.model("User", userSchema);
